### ISSUE TITLE
SÍNTESIS BUENAS PRÁCTICAS EN GESTIÓN DE PROYECTOS

### ISSUE THREAD

**Issue by Valentiin01** [SistemasTecTlaxiaco/actividad-3-sintesis-Valentiin01#2]
[SINSTESIS_GENARO SANTIAGO VALENTÍN.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-sintesis-Valentiin01/files/12516498/SINSTESIS_GENARO.SANTIAGO.VALENTIN.pdf)

**Comment by FedericoVictorianoSierra** [comment]
Calificación: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
